In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

In [53]:
train_data = pd.read_csv("cleaned_train_data.csv")
test_data = pd.read_csv(" Cleanedd_test_data.csv")

### Spliting the dataset into independent and dependent variables

In [54]:
def dependentIndependentSplit(data, target):
    X = data.drop(target, axis= 1)
    y = data[target]
    
    return X,y

In [55]:
X, y  = dependentIndependentSplit(data= train_data,
                                  target = 'Survived')

In [56]:
X

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         3    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         3    1  35.0      0      0   8.0500         2
..      ...  ...   ...    ...    ...      ...       ...
886       2    1  27.0      0      0  13.0000         2
887       1    0  19.0      0      0  30.0000         2
888       3    0  24.0      1      2  23.4500         2
889       1    1  26.0      0      0  30.0000         0
890       3    1  32.0      0      0   7.7500         1

[891 rows x 7 columns]

In [57]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

### Spliting the data into training and testing data set

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
def trainTestSplit(X,y,size = 0.2):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=size, random_state=34)
    return X_train, X_test, y_train, y_test

In [60]:
X_train, X_test, y_train, y_test = trainTestSplit(X= X,
                                                  y= y,
                                                  size= 0.2)

In [61]:
X_train

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
673       2    1  31.0      0      0  13.0000         2
255       3    0  29.0      0      2  15.2458         0
866       2    0  27.0      1      0  13.8583         0
409       3    0  24.0      3      1  25.4667         2
143       3    1  19.0      0      0   6.7500         1
..      ...  ...   ...    ...    ...      ...       ...
758       3    1  34.0      0      0   8.0500         2
873       3    1  47.0      0      0   9.0000         2
490       3    1  24.0      1      0  19.9667         2
122       2    1  32.5      1      0  30.0708         0
417       2    0  18.0      0      2  13.0000         2

[712 rows x 7 columns]

In [62]:
X_test

Pclass  Sex    Age  SibSp  Parch      Fare  Embarked
846       3    1  24.00      8      2   69.5500         2
572       1    1  36.00      0      0   26.3875         2
532       3    1  17.00      1      1    7.2292         0
714       2    1  52.00      0      0   13.0000         2
486       1    0  35.00      1      0   90.0000         2
..      ...  ...    ...    ...    ...       ...       ...
611       3    1  24.00      0      0    7.0500         2
818       3    1  43.00      0      0    6.4500         2
438       1    1  64.00      1      4  263.0000         2
469       3    0   0.75      2      1   19.2583         0
635       2    0  28.00      0      0   13.0000         2

[179 rows x 7 columns]

In [63]:
y_train

673    1
255    1
866    1
409    0
143    0
      ..
758    0
873    0
490    0
122    0
417    1
Name: Survived, Length: 712, dtype: int64

In [64]:
y_test

846    0
572    1
532    0
714    0
486    1
      ..
611    0
818    0
438    0
469    1
635    1
Name: Survived, Length: 179, dtype: int64

### Model Training

### Light XBM

In [65]:
import lightgbm as lgb

In [66]:
def train_lightgbm_model(X_train,y_train):
    """
    Train a LightGBM model on the data.

    Parameters:
    - data (pd.DataFrame): The dataset containing the features and target.
    - target (str): The name of the target column.
    - categorical_features (list): List of categorical feature column names.

    Returns:
    - model (LGBMClassifier): The trained LightGBM model.
    - accuracy (float): The accuracy of the model on the test set.
    """
    lgb_model = lgb.LGBMClassifier()
    lgb_model.fit(X_train, y_train)
    
    return lgb_model
    

In [67]:
lgb_model = train_lightgbm_model(X_train= X_train,
                                 y_train= y_train)

[LightGBM] [Info] Number of positive: 281, number of negative: 431
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000261 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 203
[LightGBM] [Info] Number of data points in the train set: 712, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.394663 -> initscore=-0.427753
[LightGBM] [Info] Start training from score -0.427753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


### XGBM

In [68]:
from xgboost import XGBClassifier as xgb

In [69]:
def train_xgboost_model(X_train, y_train):
    """
    Train an XGBoost model on the data.

    Parameters:
    - data (pd.DataFrame): The dataset containing the features and target.
    - target (str): The name of the target column.
    - categorical_features (list): List of categorical feature column names.

    Returns:
    - model (XGBClassifier): The trained XGBoost model.
    - accuracy (float): The accuracy of the model on the test set.
    """
    XGb_model = xgb(eval_metric='mlogloss',use_label_encoder=False)
    XGb_model.fit(X_train, y_train)
    
    return XGb_model

In [70]:
XGB_model = train_xgboost_model(X_train= X_train,
                                y_train= y_train)

### Evaluation

### Evaluating Model on Titanic Dataset without Target Variable in Test Data

#### Why Can't We Use the Test Data for Evaluation?

In the **Titanic dataset** provided by Kaggle, the `titanic_test.csv` file only contains the feature columns (`X_test`) and lacks the target variable (`Survived`). The target variable is crucial for evaluating the performance of a classification model, as it allows us to compare the predicted values (`y_pred`) with the actual labels (`y_test`).

Since the `titanic_test.csv` file does not have the target variable (`y_test`), **we cannot directly evaluate the model's accuracy or performance using this dataset**. Evaluation metrics such as accuracy, precision, recall, or F1-score require the true labels (`y_test`) to compute how well the model has performed.

#### What Will We Use for Evaluation?

In order to evaluate the model's performance:

1. **Use the Titanic Train Dataset**: 
   - You will use the `titanic_train.csv` dataset to train the model. This dataset contains both features (`X_train`) and the target variable (`Survived`), which is used for training the model.
   
2. **Split the Data**:
   - If you do not have a separate validation set, you can split the `titanic_train.csv` dataset into a training set and a validation set (using `train_test_split` from scikit-learn).
   - This split will give you both the feature data (`X_train`) and the target variable (`y_train`), as well as validation data (`X_val` and `y_val`), which allows for performance evaluation.

---

In [71]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [72]:
def evaluate_model(model, X_test, y_test):
    """
    Evaluate the given model using various performance metrics.

    Parameters:
    - model: The trained XGBoost or LightGBM model.
    - X_test: The feature data for testing.
    - y_test: The true labels for testing.

    Returns:
    - None
    """
    # Predicting the labels using the trained model
    y_pred = model.predict(X_test)
    
    # Calculating evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    
    # Printing evaluation results
    print("Model Evaluation Results:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print("\nConfusion Matrix:")
    print(cm)
    print("\nClassification Report:")
    print(report)

### LGBM

In [73]:
evaluate_model(model= lgb_model,
               X_test= X_test,
               y_test= y_test)

Model Evaluation Results:
Accuracy: 0.8603
Precision: 0.7903
Recall: 0.8033
F1 Score: 0.7967

Confusion Matrix:
[[105  13]
 [ 12  49]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.89      0.89       118
           1       0.79      0.80      0.80        61

    accuracy                           0.86       179
   macro avg       0.84      0.85      0.85       179
weighted avg       0.86      0.86      0.86       179



### XGBM

In [74]:
evaluate_model(model= XGB_model,
               X_test= X_test,
               y_test= y_test)

Model Evaluation Results:
Accuracy: 0.8492
Precision: 0.7742
Recall: 0.7869
F1 Score: 0.7805

Confusion Matrix:
[[104  14]
 [ 13  48]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.88      0.89       118
           1       0.77      0.79      0.78        61

    accuracy                           0.85       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.85      0.85      0.85       179



### Cross Validation

In [75]:
from sklearn.model_selection import cross_val_score

In [76]:
def cross_validate_model(model, X, y, cv=5):
    """
    Perform cross-validation on the given model and return the performance scores.

    Parameters:
    - model: The trained model (XGBoost or LightGBM).
    - X: The feature data.
    - y: The target data.
    - cv: The number of cross-validation folds (default is 5).

    Returns:
    - mean_score: The average cross-validation score.
    - std_score: The standard deviation of the cross-validation scores.
    """
    scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy')
    mean_score = np.mean(scores)
    std_score = np.std(scores)
    
    print(f"Cross-Validation Accuracy: {mean_score:.4f} ± {std_score:.4f}")
    return mean_score, std_score

### LGBM

In [77]:
mean_score_lgb, std_score_lgb = cross_validate_model(model= lgb_model,
                     X= X,
                     y= y)

[LightGBM] [Info] Number of positive: 273, number of negative: 439
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 202
[LightGBM] [Info] Number of data points in the train set: 712, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.383427 -> initscore=-0.475028
[LightGBM] [Info] Start training from score -0.475028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


In [78]:
mean_score_lgb

0.8249639068482832

In [79]:
std_score_lgb

0.03289651761947977

### XGBM

In [80]:
mean_score_Xgb, std_score_Xgb = cross_validate_model(model= XGB_model,
                     X= X,
                     y= y)

Cross-Validation Accuracy: 0.8171 ± 0.0307


In [81]:
mean_score_Xgb

0.8170924612390935

In [82]:
std_score_Xgb

0.03066235484919085

### Tuning

In [83]:
from sklearn.model_selection import RandomizedSearchCV

In [84]:
def perform_random_search(model, param_dist, X_train, y_train, n_iter=50, cv=5, scoring='accuracy', random_state=42, verbose=2):
    """
    Perform Randomized Search to tune the hyperparameters of the model.
    
    Args:
        model: The machine learning model to tune.
        param_dist (dict): The hyperparameter distribution.
        X_train (pd.DataFrame or np.ndarray): Training features.
        y_train (pd.Series or np.ndarray): Training labels.
        n_iter (int): Number of iterations for RandomizedSearchCV.
        cv (int): Number of cross-validation folds.
        scoring (str): Scoring metric for evaluation.
        random_state (int): Random state for reproducibility.
        verbose (int): Verbosity level.
        
    Returns:
        RandomizedSearchCV: Trained RandomizedSearchCV object.
    """
    random_search = RandomizedSearchCV(
        estimator=model,
        param_distributions=param_dist,
        n_iter=n_iter,
        cv=cv,
        scoring=scoring,
        verbose=verbose,
        random_state=random_state,
        n_jobs=-1  # Use all available processors
    )
    random_search.fit(X_train, y_train)
    return random_search.best_estimator_ , random_search.best_params_

### XGBM

In [85]:
xgb_param_dist = {
    'n_estimators': [100, 200, 300, 400],
    'learning_rate': np.linspace(0.01, 0.3, 10),
    'max_depth': [3, 5, 7, 9],
    'min_child_weight': [1, 3, 5, 7],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2, 0.3],
    'reg_alpha': np.logspace(-3, 1, 5),
    'reg_lambda': np.logspace(-3, 1, 5)
}

In [86]:
best_model_XGBM, best_params_XGBM = perform_random_search(model= XGB_model,
                                                                     param_dist= xgb_param_dist,
                                                                     X_train= X_train,
                                                                     y_train= y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


In [87]:
best_model_XGBM

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=0.1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.10666666666666666, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=9, max_leaves=None,
              min_child_weight=7, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=400, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [88]:
best_params_XGBM

{'subsample': 1.0,
 'reg_lambda': 0.1,
 'reg_alpha': 1.0,
 'n_estimators': 400,
 'min_child_weight': 7,
 'max_depth': 9,
 'learning_rate': 0.10666666666666666,
 'gamma': 0.1,
 'colsample_bytree': 0.8}

### LGBM

In [89]:
lgb_param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [-1, 3, 5, 7],  
    'num_leaves': [20, 31, 40],  
    'subsample': [0.8, 0.9, 1.0],  
    'colsample_bytree': [0.8, 0.9, 1.0]  
}

In [90]:
best_model_LGBM, best_params_LGBM = perform_random_search(model= lgb_model,
                                                                     param_dist= lgb_param_grid,
                                                                     X_train= X_train,
                                                                     y_train= y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[LightGBM] [Info] Number of positive: 281, number of negative: 431
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000786 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 203
[LightGBM] [Info] Number of data points in the train set: 712, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.394663 -> initscore=-0.427753
[LightGBM] [Info] Start training from score -0.427753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [W

In [91]:
best_model_LGBM

LGBMClassifier(colsample_bytree=0.9, learning_rate=0.01, max_depth=7,
               n_estimators=200, num_leaves=40)

In [92]:
best_params_LGBM

{'subsample': 1.0,
 'num_leaves': 40,
 'n_estimators': 200,
 'max_depth': 7,
 'learning_rate': 0.01,
 'colsample_bytree': 0.9}

### Model Evaluation of best models

### XGBM

In [93]:
evaluate_model(model= best_model_XGBM,
               X_test= X_test,
               y_test= y_test)

Model Evaluation Results:
Accuracy: 0.8492
Precision: 0.7833
Recall: 0.7705
F1 Score: 0.7769

Confusion Matrix:
[[105  13]
 [ 14  47]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.89      0.89       118
           1       0.78      0.77      0.78        61

    accuracy                           0.85       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.85      0.85      0.85       179



### LGBM

In [94]:
evaluate_model(model= best_model_LGBM,
               X_test= X_test,
               y_test= y_test)

Model Evaluation Results:
Accuracy: 0.8268
Precision: 0.7419
Recall: 0.7541
F1 Score: 0.7480

Confusion Matrix:
[[102  16]
 [ 15  46]]

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       118
           1       0.74      0.75      0.75        61

    accuracy                           0.83       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.83      0.83      0.83       179

