In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
data = pd.read_csv('Alphabets_data.csv')

In [3]:
data

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [5]:
data.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

### Label encoding

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()
data['letter'] = le.fit_transform(data['letter'])

### Independent and Dependent split

In [8]:
X = data.drop('letter', axis= 1)
y = data['letter']

In [9]:
X

xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0         2     8      3       5      1     8    13      0      6      6   
1         5    12      3       7      2    10     5      5      4     13   
2         4    11      6       8      6    10     6      2      6     10   
3         7    11      6       6      3     5     9      4      6      4   
4         2     1      3       1      1     8     6      6      6      6   
...     ...   ...    ...     ...    ...   ...   ...    ...    ...    ...   
19995     2     2      3       3      2     7     7      7      6      6   
19996     7    10      8       8      4     4     8      6      9     12   
19997     6     9      6       7      5     6    11      3      7     11   
19998     2     3      4       2      1     8     7      2      6     10   
19999     4     9      6       6      2     9     5      3      1      8   

       x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          10       8      0       8      0       8  
1           3       9      2       8      4      10  
2           3       7      3       7      3       9  
3           4      10      6      10      2       8  
4           5       9      1       7      5      10  
...       ...     ...    ...     ...    ...     ...  
19995       6       4      2       8      3       7  
19996       9      13      2       9      3       7  
19997       9       5      2      12      2       4  
19998       6       8      1       9      5       8  
19999       1       8      2       7      2       8  

[20000 rows x 16 columns]

In [10]:
y

0        19
1         8
2         3
3        13
4         6
         ..
19995     3
19996     2
19997    19
19998    18
19999     0
Name: letter, Length: 20000, dtype: int64

In [11]:
from keras.utils import to_categorical

In [12]:
y_encoded = to_categorical(y)

In [13]:
y_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

### Train test split

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [16]:
X_train

xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
5894      4     7      5       5      4     6     7      3      7     11   
3728      4     7      6       5      5     6     8      3      7     11   
8958      3     5      4       3      3     7     8      5      5      7   
7671      4    10      6       7      6     5     7      5      7      6   
5999      4    10      6       8      4     8    11      2      3      4   
...     ...   ...    ...     ...    ...   ...   ...    ...    ...    ...   
11284     5    11      4       6      3     7     7      4      3      9   
11964     3     7      5       5      4     9    11      6      4      6   
5390      3     4      6       3      2     9     6      2      8     10   
860       3     8      4       6      2     7     8      0      8     14   
15795     1     3      2       2      1    10     7      1      5     11   

       x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
5894        8       9      3       8      4       8  
3728        8       9      3       8      4       7  
8958        7       6      5       9      2       6  
7671        6      12      3       8      6       9  
5999       10       9      3      11      1       8  
...       ...     ...    ...     ...    ...     ...  
11284       6       7      3      10      8       7  
11964       5       7      2       8      6       4  
5390        3       7      2       7      3       9  
860         6       6      0       8      1       7  
15795       4       8      0       7      0       7  

[16000 rows x 16 columns]

In [17]:
X_test

xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
10650     3     6      5       6      4     6     7      3      8      8   
2041      4    11      6       8      8     7     8      3      5      6   
8668      3     4      5       3      2    10     2      2      1      9   
1114      2     4      2       3      2     7     7      5      7      7   
13902     4     5      5       7      3     8     7      8      6      6   
...     ...   ...    ...     ...    ...   ...   ...    ...    ...    ...   
4073      4     7      6       5      7     6     6      3      2      8   
7442      2     1      3       3      1     6    12      3      6      8   
9999      5    10      7       9      4     8     5      9      8      5   
1870      4     5      5       7      5    10    11      5      4      5   
15196     2     5      4       4      2     7    10      1      6      7   

       x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
10650       6       9      3       7      7       6  
2041        6      10      6      11      7       5  
8668        2       9      2       6      2       8  
1114        6       8      2       8      5      10  
13902       7       9      3       8      5       9  
...       ...     ...    ...     ...    ...     ...  
4073        6       7      3       7     11       2  
7442       11       7      1      11      1       7  
9999        4       8      3       8      4       8  
1870        8       8      5      10      9       5  
15196      11       8      1      11      2       8  

[4000 rows x 16 columns]

In [18]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

### Scaling the data

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
def scale_data(X_train, X_test):
    """
    Scales the training and testing data separately using StandardScaler.

    Args:
    X_train (np.array): The training features.
    X_test (np.array): The testing features.

    Returns:
    np.array: Scaled training features.
    np.array: Scaled testing features.
    """
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)  
    X_test_scaled = scaler.transform(X_test)        
    
    return X_train_scaled, X_test_scaled

In [22]:
X_train_scaled, X_test_scaled = scale_data(X_train= X_train, X_test= X_test)

In [23]:
X_test_scaled

array([[-0.53599158, -0.31546285, -0.06013429, ..., -0.86473548,
         1.28957403, -1.11481354],
       [-0.01291349,  1.19809287,  0.43581861, ...,  1.72720301,
         1.28957403, -1.73329539],
       [-0.53599158, -0.92088514, -0.06013429, ..., -1.5127201 ,
        -0.65897489,  0.12215017],
       ...,
       [ 0.5101646 ,  0.89538173,  0.9317715 , ..., -0.21675086,
         0.12044468,  0.12215017],
       [-0.01291349, -0.618174  , -0.06013429, ...,  1.07921839,
         2.06899359, -1.73329539],
       [-1.05906966, -0.618174  , -0.55608718, ...,  1.72720301,
        -0.65897489,  0.12215017]])

In [24]:
X_train_scaled

array([[-0.01291349, -0.01275171, -0.06013429, ..., -0.21675086,
         0.12044468,  0.12215017],
       [-0.01291349, -0.01275171,  0.43581861, ..., -0.21675086,
         0.12044468, -0.49633169],
       [-0.53599158, -0.618174  , -0.55608718, ...,  0.43123377,
        -0.65897489, -1.11481354],
       ...,
       [-0.53599158, -0.92088514,  0.43581861, ..., -0.86473548,
        -0.2692651 ,  0.74063202],
       [-0.53599158,  0.28995944, -0.55608718, ..., -0.21675086,
        -1.04868467, -0.49633169],
       [-1.58214775, -1.22359629, -1.54799298, ..., -0.86473548,
        -1.43839445, -0.49633169]])

In [25]:
X_train = pd.DataFrame(data= X_train_scaled,columns=X.columns)
X_test = pd.DataFrame(data= X_test_scaled, columns= X.columns)

In [26]:
X_train

xbox      ybox     width    height     onpix      xbar      ybar  \
0     -0.012913 -0.012752 -0.060134 -0.166388  0.225460 -0.442033 -0.212561   
1     -0.012913 -0.012752  0.435819 -0.166388  0.682088 -0.442033  0.217398   
2     -0.535992 -0.618174 -0.556087 -1.048935 -0.231168  0.050414  0.217398   
3     -0.012913  0.895382  0.435819  0.716160  1.138715 -0.934480 -0.212561   
4     -0.012913  0.895382  0.435819  1.157434  0.225460  0.542861  1.507277   
...         ...       ...       ...       ...       ...       ...       ...   
15995  0.510165  1.198093 -0.556087  0.274886 -0.231168  0.050414 -0.212561   
15996 -0.535992 -0.012752 -0.060134 -0.166388  0.225460  1.035308  1.507277   
15997 -0.535992 -0.920885  0.435819 -1.048935 -0.687795  1.035308 -0.642521   
15998 -0.535992  0.289959 -0.556087  0.274886 -0.687795  0.050414  0.217398   
15999 -1.582148 -1.223596 -1.547993 -1.490209 -1.144423  1.527755 -0.212561   

          x2bar     y2bar     xybar    x2ybar    xy2bar     xedge    xedgey  \
0     -0.603148  0.761007  1.088793  0.590471  0.513941 -0.019484 -0.216751   
1     -0.603148  0.761007  1.088793  0.590471  0.513941 -0.019484 -0.216751   
2      0.134619 -0.075322 -0.516763  0.209675 -0.926257  0.838118  0.431234   
3      0.134619  0.761007 -0.918152 -0.171120  1.954139 -0.019484 -0.216751   
4     -0.972031 -0.911651 -1.720930  1.352061  0.513941 -0.019484  1.727203   
...         ...       ...       ...       ...       ...       ...       ...   
15995 -0.234264 -0.911651  0.286015 -0.171120 -0.446191 -0.019484  1.079218   
15996  0.503503 -0.493487 -0.918152 -0.551915 -0.446191 -0.448284 -0.216751   
15997 -0.972031  1.179172  0.687404 -1.313506 -0.446191 -0.448284 -0.864735   
15998 -1.709798  1.179172  2.292960 -0.171120 -0.926257 -1.305886 -0.216751   
15999 -1.340915 -0.075322  1.088793 -0.932710  0.033875 -1.305886 -0.864735   

          yedge    yedgex  
0      0.120445  0.122150  
1      0.120445 -0.496332  
2     -0.658975 -1.114814  
3      0.899864  0.740632  
4     -1.048685  0.122150  
...         ...       ...  
15995  1.679284 -0.496332  
15996  0.899864 -2.351777  
15997 -0.269265  0.740632  
15998 -1.048685 -0.496332  
15999 -1.438394 -0.496332  

[16000 rows x 16 columns]

In [27]:
X_test

xbox      ybox     width    height     onpix      xbar      ybar  \
0    -0.535992 -0.315463 -0.060134  0.274886  0.225460 -0.442033 -0.212561   
1    -0.012913  1.198093  0.435819  1.157434  2.051970  0.050414  0.217398   
2    -0.535992 -0.920885 -0.060134 -1.048935 -0.687795  1.527755 -2.362360   
3    -1.059070 -0.920885 -1.547993 -1.048935 -0.687795  0.050414 -0.212561   
4    -0.012913 -0.618174 -0.060134  0.716160 -0.231168  0.542861 -0.212561   
...        ...       ...       ...       ...       ...       ...       ...   
3995 -0.012913 -0.012752  0.435819 -0.166388  1.595343 -0.442033 -0.642521   
3996 -1.059070 -1.829019 -1.052040 -1.048935 -1.144423 -0.442033  1.937237   
3997  0.510165  0.895382  0.931772  1.598707  0.225460  0.542861 -1.072481   
3998 -0.012913 -0.618174 -0.060134  0.716160  0.682088  1.527755  1.507277   
3999 -1.059070 -0.618174 -0.556087 -0.607662 -0.687795  0.050414  1.077318   

         x2bar     y2bar     xybar    x2ybar    xy2bar     xedge    xedgey  \
0    -0.603148  1.179172 -0.115374 -0.171120  0.513941 -0.019484 -0.864735   
1    -0.603148 -0.075322 -0.918152 -0.171120  0.994007  1.266919  1.727203   
2    -0.972031 -1.747981  0.286015 -1.694301  0.513941 -0.448284 -1.512720   
3     0.134619  0.761007 -0.516763 -0.171120  0.033875 -0.448284 -0.216751   
4     1.241270  0.342843 -0.918152  0.209675  0.513941 -0.019484 -0.216751   
...        ...       ...       ...       ...       ...       ...       ...   
3995 -0.603148 -1.329816 -0.115374 -0.171120 -0.446191 -0.019484 -0.864735   
3996 -0.603148  0.342843 -0.115374  1.732856 -0.446191 -0.877085  1.727203   
3997  1.610154  1.179172 -1.319541 -0.932710  0.033875 -0.019484 -0.216751   
3998  0.134619 -0.493487 -1.319541  0.590471  0.033875  0.838118  1.079218   
3999 -1.340915  0.342843 -0.516763  1.732856  0.033875 -0.877085  1.727203   

         yedge    yedgex  
0     1.289574 -1.114814  
1     1.289574 -1.733295  
2    -0.658975  0.122150  
3     0.510154  1.359114  
4     0.510154  0.740632  
...        ...       ...  
3995  2.848413 -3.588741  
3996 -1.048685 -0.496332  
3997  0.120445  0.122150  
3998  2.068994 -1.733295  
3999 -0.658975  0.122150  

[4000 rows x 16 columns]

### Model Training

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Function to create a model
def create_model(hidden_layers=(64,), activation='relu', learning_rate=0.001, dropout_rate=0.2, input_dim=None, output_dim=None):
    model = Sequential()
    model.add(Dense(hidden_layers[0], activation=activation, input_dim=input_dim))
    model.add(Dropout(dropout_rate))
    
    for neurons in hidden_layers[1:]:
        model.add(Dense(neurons, activation=activation))
        model.add(Dropout(dropout_rate))
    
    model.add(Dense(output_dim, activation='softmax'))
    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    
    return model

# Function to train and evaluate a model
def train_evaluate_model(model, X_train, y_train, batch_size=32, epochs=50):
    early_stopping = EarlyStopping(monitor='val_accuracy', patience=2, restore_best_weights=True, verbose=1)
    history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=0, validation_split=0.2, callbacks=[early_stopping])
    return history

# Random search function with early stopping
def random_search_tuning(X_train, y_train, n_iter=15, n_folds=3, early_stop_threshold=0.98):
    param_distributions = {
        'hidden_layers': [(64,), (128,)],
        'activation': ['relu'],
        'learning_rate': [0.001],
        'dropout_rate': [0.2],
        'batch_size': [32, 64],
        'epochs': [30]  # Start with fewer epochs
    }

    kf = KFold(n_splits=n_folds, shuffle=True)
    best_avg_accuracy = 0
    best_params = None
    best_model = None

    # Convert X_train from DataFrame to NumPy array
    X_train = X_train.to_numpy()

    for i in range(n_iter):
        params = {
            'hidden_layers': param_distributions['hidden_layers'][np.random.randint(len(param_distributions['hidden_layers']))],
            'activation': np.random.choice(param_distributions['activation']),
            'learning_rate': np.random.choice(param_distributions['learning_rate']),
            'dropout_rate': np.random.choice(param_distributions['dropout_rate']),
            'batch_size': np.random.choice(param_distributions['batch_size']),
            'epochs': np.random.choice(param_distributions['epochs'])
        }
        
        fold_accuracies = []
        for train_idx, val_idx in kf.split(X_train):
            X_fold_train, X_fold_val = X_train[train_idx], X_train[val_idx]
            y_fold_train, y_fold_val = y_train[train_idx], y_train[val_idx]
            
            model = create_model(
                hidden_layers=params['hidden_layers'],
                activation=params['activation'],
                learning_rate=params['learning_rate'],
                dropout_rate=params['dropout_rate'],
                input_dim=X_train.shape[1],
                output_dim=y_train.shape[1]
            )
            
            history = train_evaluate_model(
                model, X_fold_train, y_fold_train,
                batch_size=params['batch_size'],
                epochs=params['epochs']
            )
            
            val_loss, val_accuracy = model.evaluate(X_fold_val, y_fold_val, verbose=0)
            fold_accuracies.append(val_accuracy)
        
        avg_accuracy = np.mean(fold_accuracies)
        print(f"Iteration {i+1}/{n_iter} | Parameters: {params} | Average CV Accuracy: {avg_accuracy:.4f}")
        
        if avg_accuracy > best_avg_accuracy:
            best_avg_accuracy = avg_accuracy
            best_params = params
            best_model = model
            
        # **Early stopping based on high accuracy**
        if best_avg_accuracy >= early_stop_threshold:
            print(f"Early stopping at iteration {i+1} with accuracy {best_avg_accuracy:.4f}")
            break  

    return best_model, best_params

if __name__ == "__main__":
    # Perform Random Search Tuning
    best_model_random, best_params_random = random_search_tuning(X_train, y_train)

Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 21.
Restoring model weights from the end of the best epoch: 30.
Restoring model weights from the end of the best epoch: 30.
Iteration 1/15 | Parameters: {'hidden_layers': (64,), 'activation': np.str_('relu'), 'learning_rate': np.float64(0.001), 'dropout_rate': np.float64(0.2), 'batch_size': np.int64(32), 'epochs': np.int64(30)} | Average CV Accuracy: 0.8636
Epoch 29: early stopping
Restoring model weights from the end of the best epoch: 27.
Epoch 25: early stopping
Restoring model weights from the end of the best epoch: 23.
Restoring model weights from the end of the best epoch: 30.
Iteration 2/15 | Parameters: {'hidden_layers': (64,), 'activation': np.str_('relu'), 'learning_rate': np.float64(0.001), 'dropout_rate': np.float64(0.2), 'batch_size': np.int64(64), 'epochs': np.int64(30)} | Average CV Accuracy: 0.8502
Restoring model weights from the end of the best epoch: 30.
Restoring model weights from the 

### Best model

In [36]:
best_params_random

{'hidden_layers': (128,),
 'activation': np.str_('relu'),
 'learning_rate': np.float64(0.001),
 'dropout_rate': np.float64(0.2),
 'batch_size': np.int64(64),
 'epochs': np.int64(30)}

In [37]:
best_model_random

<Sequential name=sequential_230, built=True>

### Base model

In [40]:
def train_base_model_default(X_train, y_train, X_test, y_test):
    """
    Trains a base model with default hyperparameters (no tuning).
    
    Parameters:
    - X_train, y_train: Training dataset.
    - X_test, y_test: Test dataset for evaluation.
    
    Returns:
    - trained_model: The trained Keras model.
    - history: Training history object.
    """
    # Define base model hyperparameters (default values)
    base_params = {
        'hidden_layers': (64,),           # Default: 64 neurons in 1 hidden layer
        'activation': 'relu',             # Default: ReLU activation
        'learning_rate': 0.001,           # Default: learning rate of 0.001
        'dropout_rate': 0.2,              # Default: dropout rate of 0.2
        'batch_size': 32,                 # Default: batch size of 32
        'epochs': 50                      # Default: 50 epochs
    }

    # Initialize model using the default parameters
    model = create_model(
        hidden_layers=base_params['hidden_layers'],
        activation=base_params['activation'],
        learning_rate=base_params['learning_rate'],
        dropout_rate=base_params['dropout_rate'],
        input_dim=X_train.shape[1],       # Number of input features
        output_dim=y_train.shape[1]       # Number of output classes
    )

    # Train the model
    history = train_evaluate_model(
        model, X_train, y_train,
        batch_size=base_params['batch_size'],
        epochs=base_params['epochs']
    )

    # Evaluate model on test data
    test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=1)
    print(f"Test Accuracy: {test_accuracy:.4f}")

    return model, history

In [41]:
base_model, base_history = train_base_model_default(X_train, y_train, X_test, y_test)

Epoch 23: early stopping
Restoring model weights from the end of the best epoch: 21.
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8827 - loss: 0.3983
Test Accuracy: 0.8857


### Model Evaluation

In [42]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model, X_test, y_test):
    """
    Evaluates the model using accuracy, precision, recall, and F1-score.

    Parameters:
    - model: Trained model to evaluate.
    - X_test: Test dataset features.
    - y_test: True labels of the test dataset.

    Returns:
    - A dictionary containing accuracy, precision, recall, and F1-score.
    """
    y_pred = model.predict(X_test)
    y_pred_classes = y_pred.argmax(axis=1)  # Convert probabilities to class labels
    y_true_classes = y_test.argmax(axis=1)  # Convert one-hot encoded labels to class labels

    metrics = {
        "Accuracy": accuracy_score(y_true_classes, y_pred_classes),
        "Precision": precision_score(y_true_classes, y_pred_classes, average="weighted"),
        "Recall": recall_score(y_true_classes, y_pred_classes, average="weighted"),
        "F1-Score": f1_score(y_true_classes, y_pred_classes, average="weighted"),
    }

    return metrics

In [43]:
results = evaluate_model(best_model_random, X_test, y_test)
print(results)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
{'Accuracy': 0.90025, 'Precision': 0.9020621448762338, 'Recall': 0.90025, 'F1-Score': 0.9002031904802128}


In [44]:
results = evaluate_model(base_model, X_test, y_test)
print(results)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step
{'Accuracy': 0.88575, 'Precision': 0.8898934480417653, 'Recall': 0.88575, 'F1-Score': 0.8863986441927629}
