In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

## Loading Data

In [2]:
df = pd.read_csv('Cleaned_ToyotaData.csv')

In [3]:
df.head()

Price  Age_08_04       KM    HP  Automatic      cc  Doors  Cylinders  \
0  13500.0       23.0  46986.0  90.0        0.0  1900.0    3.0        4.0   
1  13750.0       23.0  72937.0  90.0        0.0  1900.0    3.0        4.0   
2  13950.0       24.0  41711.0  90.0        0.0  1900.0    3.0        4.0   
3  14950.0       26.0  48000.0  90.0        0.0  1900.0    3.0        4.0   
4  13750.0       30.0  38500.0  90.0        0.0  1900.0    3.0        4.0   

   Gears  Weight  Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  
0    5.0  1152.5              0                 1                 0  
1    5.0  1152.5              0                 1                 0  
2    5.0  1152.5              0                 1                 0  
3    5.0  1152.5              0                 1                 0  
4    5.0  1152.5              0                 1                 0

In [4]:
df.shape

(1436, 13)

## Spliting the data into independent and dependent

In [5]:
X = df.drop('Price',axis=1)
y = df['Price']

In [6]:
X

Age_08_04       KM     HP  Automatic      cc  Doors  Cylinders  Gears  \
0          23.0  46986.0   90.0        0.0  1900.0    3.0        4.0    5.0   
1          23.0  72937.0   90.0        0.0  1900.0    3.0        4.0    5.0   
2          24.0  41711.0   90.0        0.0  1900.0    3.0        4.0    5.0   
3          26.0  48000.0   90.0        0.0  1900.0    3.0        4.0    5.0   
4          30.0  38500.0   90.0        0.0  1900.0    3.0        4.0    5.0   
...         ...      ...    ...        ...     ...    ...        ...    ...   
1431       69.0  20544.0   86.0        0.0  1300.0    3.0        4.0    5.0   
1432       72.0  19000.0   86.0        0.0  1300.0    3.0        4.0    5.0   
1433       71.0  17016.0   86.0        0.0  1300.0    3.0        4.0    5.0   
1434       70.0  16916.0   86.0        0.0  1300.0    3.0        4.0    5.0   
1435       76.0      1.0  110.0        0.0  1600.0    5.0        4.0    5.0   

      Weight  Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  
0     1152.5              0                 1                 0  
1     1152.5              0                 1                 0  
2     1152.5              0                 1                 0  
3     1152.5              0                 1                 0  
4     1152.5              0                 1                 0  
...      ...            ...               ...               ...  
1431  1025.0              0                 0                 1  
1432  1015.0              0                 0                 1  
1433  1015.0              0                 0                 1  
1434  1015.0              0                 0                 1  
1435  1114.0              0                 0                 1  

[1436 rows x 12 columns]

In [7]:
y

0       13500.0
1       13750.0
2       13950.0
3       14950.0
4       13750.0
         ...   
1431     7500.0
1432    10845.0
1433     8500.0
1434     7250.0
1435     6950.0
Name: Price, Length: 1436, dtype: float64

## Spliting the data as training and test sets

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train , X_test , y_train, y_test = train_test_split(X,y,test_size= 0.3, random_state=32)

In [10]:
X_train

Age_08_04        KM     HP  Automatic      cc  Doors  Cylinders  Gears  \
322        37.0   36074.0  110.0        0.0  1600.0    5.0        4.0    5.0   
1419       75.0   38945.0  110.0        0.0  1600.0    3.0        4.0    5.0   
384        54.0  149329.0   72.0        0.0  1900.0    5.0        4.0    5.0   
1099       76.0  124591.0  110.0        0.0  1600.0    5.0        4.0    5.0   
556        47.0   40361.0  110.0        0.0  1600.0    5.0        4.0    5.0   
...         ...       ...    ...        ...     ...    ...        ...    ...   
1427       71.0   29000.0   86.0        0.0  1300.0    3.0        4.0    5.0   
88         19.0   51884.0   97.0        0.0  1400.0    3.0        4.0    5.0   
892        57.0   61000.0  110.0        0.0  1600.0    3.0        4.0    5.0   
1334       71.0   64000.0  110.0        0.0  1600.0    5.0        4.0    5.0   
727        59.0   86888.0  110.0        0.0  1600.0    3.0        4.0    5.0   

      Weight  Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  
322   1075.0              0                 0                 1  
1419  1050.0              0                 0                 1  
384   1135.0              0                 1                 0  
1099  1075.0              0                 0                 1  
556   1090.0              0                 0                 1  
...      ...            ...               ...               ...  
1427  1045.0              0                 0                 1  
88    1100.0              0                 0                 1  
892   1050.0              0                 0                 1  
1334  1070.0              0                 0                 1  
727   1050.0              0                 0                 1  

[1005 rows x 12 columns]

In [11]:
X_test

Age_08_04        KM     HP  Automatic      cc  Doors  Cylinders  Gears  \
817        67.0   70552.0  110.0        0.0  1600.0    5.0        4.0    5.0   
389        54.0  138394.0   69.0        0.0  1900.0    4.0        4.0    5.0   
1338       80.0   63500.0  110.0        0.0  1600.0    3.0        4.0    5.0   
390        55.0  137000.0   72.0        0.0  1900.0    5.0        4.0    5.0   
59         30.0   38950.0  110.0        0.0  1600.0    5.0        4.0    5.0   
...         ...       ...    ...        ...     ...    ...        ...    ...   
1128       78.0  109263.0  110.0        0.0  1600.0    5.0        4.0    5.0   
960        66.0   50806.0   86.0        0.0  1300.0    3.0        4.0    5.0   
948        68.0   53000.0   86.0        0.0  1300.0    3.0        4.0    5.0   
1265       78.0   75226.0  110.0        0.0  1600.0    4.0        4.0    5.0   
173         8.0   10000.0   97.0        0.0  1400.0    5.0        4.0    5.0   

      Weight  Fuel_Type_CNG  Fuel_Type_Diesel  Fuel_Type_Petrol  
817   1075.0              0                 0                 1  
389   1095.0              0                 1                 0  
1338  1050.0              0                 0                 1  
390   1135.0              0                 1                 0  
59    1130.0              0                 0                 1  
...      ...            ...               ...               ...  
1128  1070.0              0                 0                 1  
960   1152.5              0                 0                 1  
948   1015.0              0                 0                 1  
1265  1035.0              0                 0                 1  
173   1110.0              0                 0                 1  

[431 rows x 12 columns]

## Standardization 

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test) #Just use tranform on test data to avoid data leakage

In [15]:
X_train

array([[-0.98586239, -0.8829333 ,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [ 1.02149977, -0.79931334,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [-0.08783195,  2.41570074, -2.24879265, ..., -0.10519695,
         2.92770022, -2.76835567],
       ...,
       [ 0.07064401, -0.15694546,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [ 0.81019849, -0.06956829,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [ 0.17629465,  0.59706132,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526]])

In [16]:
X_test

array([[ 0.59889721,  0.12126347,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [-0.08783195,  2.09721093, -2.48119512, ..., -0.10519695,
         2.92770022, -2.76835567],
       [ 1.28562636, -0.08413115,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       ...,
       [ 0.65172253, -0.38995127, -1.16424776, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [ 1.17997573,  0.25739711,  0.69497205, ..., -0.10519695,
        -0.34156503,  0.36122526],
       [-2.51779666, -1.64235746, -0.31210535, ..., -0.10519695,
        -0.34156503,  0.36122526]])

# Model Training

# Simple Linear Regression Model

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

In [19]:
model.fit(X_train,y_train)

LinearRegression()

## Prediction

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([ 9520.83762238,  8468.91810948,  7820.55853767,  9355.62558216,
       15319.33035985, 11004.86673911,  7917.48271118, 17803.62059831,
       12103.39050882, 11310.54658313,  8240.07208791, 13117.61919018,
        8662.86164206,  8738.16083516, 11460.54765561,  8140.10400835,
       10755.82317899,  8522.33525505,  8944.16145734,  8544.99418174,
       15964.39392483, 10523.02073513, 13068.60352501,  7835.433049  ,
        9224.47329115, 12674.01523275,  7959.06193407, 10298.02649518,
       11133.75636323,  8605.6739628 ,  9162.6143622 ,  8262.65489923,
       10070.74488702,  9362.42896195,  7827.06644061,  9377.00716452,
       11069.62870455,  9913.20484076,  9889.74958234, 12701.17099326,
       10285.09021481,  7904.4828653 , 10775.1110177 , 17375.90121628,
       10791.0287054 , 11201.22858054, 10603.88269517, 11314.19603793,
       16253.15166332,  7109.26027149,  9573.52946128,  8178.69233574,
        9450.52982426,  8443.00153851,  7605.19001334,  8600.51853155,
      

## Model Evaluation

### Tranning accuracy

In [22]:
model.score(X_train,y_train)

0.871811458638875

In [23]:
from sklearn.metrics import mean_squared_error,r2_score

In [24]:
mean_squared_error(y_test,y_pred)

np.float64(1228001.7818030724)

### Test Accuracy

In [25]:
r2_score(y_test,y_pred)

0.8500060152010736

### Coefficieants

In [26]:
model.coef_

array([-2.01795315e+03, -5.25665209e+02,  3.24817272e+02,  1.56319402e-13,
       -3.65982283e+02, -9.56421451e+01, -7.10542736e-15, -7.10542736e-14,
        9.36597558e+02, -7.81305414e+01, -3.70035296e+01,  6.08632818e+01])

### Intercept

In [27]:
model.intercept_

np.float64(10560.871641791047)

## Lasso Regularization

In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso

In [29]:
model = Lasso()

In [33]:
parameter = {'alpha' : np.logspace(-4, 0, 10)}

In [36]:
grid = GridSearchCV(model,parameter,cv= 5,scoring= 'neg_mean_squared_error')

In [37]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': array([1.00000000e-04, 2.78255940e-04, 7.74263683e-04, 2.15443469e-03,
       5.99484250e-03, 1.66810054e-02, 4.64158883e-02, 1.29154967e-01,
       3.59381366e-01, 1.00000000e+00])},
             scoring='neg_mean_squared_error')

In [38]:
# Best alpha value found
best_alpha = grid.best_params_['alpha']
print(f"Best alpha: {best_alpha}")

Best alpha: 0.0001


In [39]:
# Train a Lasso model using the best alpha value
best_lasso = Lasso(alpha=best_alpha)
best_lasso.fit(X_train, y_train)

Lasso(alpha=np.float64(0.0001))

In [40]:
# Make predictions on the test data
y_pred = best_lasso.predict(X_test)

In [41]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)  # Mean Squared Error
r2 = r2_score(y_test, y_pred)  # R-squared score

In [42]:
# Display the results
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')
print('Coefficients:', best_lasso.coef_)
print('Intercept:', best_lasso.intercept_)

Mean Squared Error: 1228001.798170577
R-squared: 0.8500060132018686
Coefficients: [-2.01795327e+03 -5.25665324e+02  3.24816271e+02  0.00000000e+00
 -3.65980887e+02 -9.56418806e+01  0.00000000e+00  0.00000000e+00
  9.36596948e+02 -9.75870597e+01 -9.42045033e+01  1.11039744e+00]
Intercept: 10560.871641791047


## Ridge

In [43]:
from sklearn.linear_model import Ridge

In [44]:
model = Ridge()

In [45]:
# Define a range of alpha values for hyperparameter tuning
alpha_range = {'alpha': np.logspace(-4, 2, 10)}  # From 0.0001 to 100

In [46]:
# Use GridSearchCV to find the best alpha
grid = GridSearchCV(estimator=model, param_grid=alpha_range, cv=5, scoring='neg_mean_squared_error')

In [47]:
# Fit the grid search to the training data
grid.fit(X_train, y_train)


GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': array([1.00000000e-04, 4.64158883e-04, 2.15443469e-03, 1.00000000e-02,
       4.64158883e-02, 2.15443469e-01, 1.00000000e+00, 4.64158883e+00,
       2.15443469e+01, 1.00000000e+02])},
             scoring='neg_mean_squared_error')

In [48]:
# Best alpha value found
best_alpha = grid.best_params_['alpha']
print(f"Best alpha: {best_alpha}")

Best alpha: 1.0


In [49]:
# Train a Ridge model using the best alpha value
best_ridge = Ridge(alpha=best_alpha)
best_ridge.fit(X_train, y_train)

Ridge(alpha=np.float64(1.0))

In [50]:
# Make predictions on the test data
y_pred = best_ridge.predict(X_test)

In [51]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)  # Mean Squared Error
r2 = r2_score(y_test, y_pred)  # R-squared score

In [52]:
# Display the results
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')
print('Coefficients:', best_ridge.coef_)
print('Intercept:', best_ridge.intercept_)

Mean Squared Error: 1228092.6949594186
R-squared: 0.8499949106352715
Coefficients: [-2015.88195898  -527.40715048   320.30659604     0.
  -359.69069643   -94.8222497      0.             0.
   934.84894628   -76.9435971    -39.89119221    63.24107315]
Intercept: 10560.871641791047


## Elastic Net

In [53]:
from sklearn.linear_model import ElasticNet

In [54]:
model = ElasticNet()

In [56]:
# Define a grid of alpha and l1_ratio values for hyperparameter tuning
param_grid = {
    'alpha': np.logspace(-4, 0, 10),  # From 0.0001 to 1
    'l1_ratio': np.linspace(0, 1, 10)  # From 0 (Ridge) to 1 (Lasso)
}

In [57]:
# Use GridSearchCV to find the best combination of alpha and l1_ratio
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')

In [58]:
# Fit the grid search to the training data
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': array([1.00000000e-04, 2.78255940e-04, 7.74263683e-04, 2.15443469e-03,
       5.99484250e-03, 1.66810054e-02, 4.64158883e-02, 1.29154967e-01,
       3.59381366e-01, 1.00000000e+00]),
                         'l1_ratio': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])},
             scoring='neg_mean_squared_error')

In [59]:
# Best alpha and l1_ratio values found
best_alpha = grid_search.best_params_['alpha']
best_l1_ratio = grid_search.best_params_['l1_ratio']
print(f"Best alpha: {best_alpha}")
print(f"Best l1_ratio: {best_l1_ratio}")

Best alpha: 0.005994842503189409
Best l1_ratio: 0.5555555555555556


In [60]:
# Train an Elastic Net model using the best alpha and l1_ratio values
best_elastic_net = ElasticNet(alpha=best_alpha, l1_ratio=best_l1_ratio)
best_elastic_net.fit(X_train, y_train)

ElasticNet(alpha=np.float64(0.005994842503189409),
           l1_ratio=np.float64(0.5555555555555556))

In [61]:
# Make predictions on the test data
y_pred = best_elastic_net.predict(X_test)

In [62]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)  # Mean Squared Error
r2 = r2_score(y_test, y_pred)  # R-squared score

In [63]:
# Display the results
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')
print('Coefficients:', best_elastic_net.coef_)
print('Intercept:', best_elastic_net.intercept_)

Mean Squared Error: 1228270.0081996175
R-squared: 0.8499732527518311
Coefficients: [-2012.37526877  -530.27301302   313.29083691     0.
  -349.77156439   -93.4518802      0.             0.
   931.95637676   -75.26973259   -44.88781787    66.29341322]
Intercept: 10560.871641791047
